---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mip-argo-project-infrastructure
  namespace: argocd-mip-team
spec:
  description: Core infrastructure components and ApplicationSets
  sourceRepos:
    - https://github.com/NeuroTech-Platform/mip-infra.git
    - git@github.com:NeuroTech-Platform/mip-deployments.git
  destinations:
    - namespace: argocd-mip-team
      server: https://kubernetes.default.svc
    # Allow network policy deployment to federation namespaces
    - namespace: 'federation-*'
      server: https://kubernetes.default.svc
    # Allow network policy deployment to common namespaces
    - namespace: 'mip-common-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: argoproj.io
      kind: ApplicationSet
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: AppProject
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: ApplicationSet
    - group: argoproj.io
      kind: AppProject
    - group: networking.k8s.io
      kind: NetworkPolicy
  # Explicitly blacklist sensitive resources to be future proof
  clusterResourceBlacklist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
  syncWindows:
    - kind: allow
      schedule: '* * * * *'
      duration: 24h
      applications: ['*']
  roles:
    - name: infrastructure-admin
      description: Full access to infrastructure resources
      policies:
        - p, proj:mip-argo-project-infrastructure:infrastructure-admin, applications,
          *, mip-argo-project-infrastructure/*, allow
      groups: [argocd-admins]
