---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: federation-a
  namespace: argocd-mip-team
spec:
  project: mip-argo-project-federations
  source:
    repoURL: https://github.com/NeuroTech-Platform/mip-infra.git
    targetRevision: main
    path: deployments/local/federations/federation-A
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-mip-team
  syncPolicy:
    syncOptions: 
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
