---
extends: default
rules:
  line-length:
    max: 120
    level: warning
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: false
  empty-values:
    forbid-in-block-mappings: true
  trailing-spaces: enable
  new-line-at-end-of-file: enable
