---
# Namespace isolation policy for {{.Values.targetNamespace}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: federation-namespace-isolation
  namespace: {{.Values.targetNamespace}}
  labels:
    app.kubernetes.io/name: federation-network-policy
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    mip.namespace-type: federation
    mip.federation-type: {{.Values.federationType}}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from pods within the same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{.Values.targetNamespace}}
    # Allow traffic from ArgoCD for management
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{.Values.argoCDNamespace}}
  egress:
    # Allow traffic to pods within the same namespace
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{.Values.targetNamespace}}
    # Allow DNS queries to kube-system
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{.Values.systemNamespace}}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS egress for external dependencies
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow HTTP egress for external dependencies
    - to: []
      ports:
        - protocol: TCP
          port: 80
---
# Default deny policy for {{.Values.targetNamespace}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: federation-default-deny
  namespace: {{.Values.targetNamespace}}
  labels:
    app.kubernetes.io/name: federation-network-policy
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/managed-by: {{.Release.Service}}
    mip.namespace-type: federation
    mip.federation-type: {{.Values.federationType}}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress 