# Default values for common network policy templates
# These are overridden by ApplicationSet parameters

# Target namespace (set by ApplicationSet parameter)
targetNamespace: ""

# ArgoCD namespace for management access
argoCDNamespace: argocd-mip-team

# Kubernetes system namespace for DNS
systemNamespace: kube-system

# Federation access control (simplified - no namespace lists needed)
federationAccess:
  local:
    enabled: false
    allowedCommonNamespaces: []
  hybrid:
    enabled: false
    allowedCommonNamespaces: []

# Global network policy settings
networkPolicy:
  allowExternalHTTP: true
  allowExternalHTTPS: true
  dns:
    allowUDP: true
    allowTCP: true
    port: 53
  enableDefaultDeny: true 