{{- if and .Values.alertNotifier.enabled (.Values.alertNotifier.secret.create | default false) (not .Values.alertNotifier.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eck-stack.alertNotifier.secretName" . }}
  labels:
    {{- include "eck-stack.alertNotifier.labels" . | nindent 4 }}
stringData:
  {{- with .Values.alertNotifier.secret.data.esUrl }}
  es-url: {{ . | quote }}
  {{- end }}
  {{- with .Values.alertNotifier.secret.data.esUser }}
  es-user: {{ . | quote }}
  {{- end }}
  {{- with .Values.alertNotifier.secret.data.esPass }}
  es-pass: {{ . | quote }}
  {{- end }}
  {{- with .Values.alertNotifier.secret.data.teamsWebhook }}
  teams-webhook: {{ . | quote }}
  {{- end }}
{{- end }}
