{{- if .Values.observability.metricbeat.enabled }}
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: {{ .Release.Name }}-metricbeat
  namespace: {{ include "eck-stack.operatorNamespace" . }}
  labels:
    app.kubernetes.io/name: metricbeat
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.observability.metricbeat.version | quote }}
spec:
  type: metricbeat
  version: {{ .Values.observability.metricbeat.version | quote }}
  elasticsearchRef:
    name: {{ .Values.elasticsearch.name }}
    namespace: {{ .Values.elasticsearch.namespace | default (include "eck-stack.operatorNamespace" .) }}
  daemonSet:
    podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: metricbeat
      spec:
        automountServiceAccountToken: true
        serviceAccountName: {{ .Release.Name }}-metricbeat
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        tolerations:
          - effect: NoSchedule
            operator: Exists
        containers:
          - name: metricbeat
            env:
              - name: NODE_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              - name: NODE_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP
              - name: ELASTICSEARCH_HOSTS
                value: https://{{ .Values.elasticsearch.name }}-es-http.{{ .Values.elasticsearch.namespace | default (include "eck-stack.operatorNamespace" .) }}.svc:9200
              - name: ELASTICSEARCH_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: {{ printf "%s-%s-beat-user" (include "eck-stack.operatorNamespace" .) (printf "%s-metricbeat" .Release.Name) }}
                    key: name
              - name: ELASTICSEARCH_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-metricbeat-beat-user
                    key: {{ printf "%s-%s-beat-user" (include "eck-stack.operatorNamespace" .) (printf "%s-metricbeat" .Release.Name) }}
            volumeMounts:
              - name: proc
                mountPath: /hostfs/proc
                readOnly: true
              - name: cgroup
                mountPath: /hostfs/sys/fs/cgroup
                readOnly: true
              - name: rootfs
                mountPath: /hostfs
                readOnly: true
              - name: data
                mountPath: /usr/share/metricbeat/data
            {{- with .Values.observability.metricbeat.resources }}
            resources:
{{ toYaml . | indent 14 }}
            {{- end }}
        volumes:
          - name: data
            emptyDir: {}
          - name: proc
            hostPath:
              path: /proc
          - name: cgroup
            hostPath:
              path: /sys/fs/cgroup
          - name: rootfs
            hostPath:
              path: /
  config:
{{ toYaml .Values.observability.metricbeat.config | indent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-metricbeat
  namespace: {{ include "eck-stack.operatorNamespace" . }}
{{- end }}
