---
# ServiceAccount for the secret copier job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: broker-secret-copier
  namespace: submariner-k8s-broker
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
---
# Job to copy the secret from broker to operator namespace
# Note: RBAC for this job is in base/mip-infrastructure/rbac/submariner-rbac.yaml
# and must be applied manually before ArgoCD deployment
apiVersion: batch/v1
kind: Job
metadata:
  name: copy-broker-secret
  namespace: submariner-k8s-broker
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: broker-secret-copier
    spec:
      serviceAccountName: broker-secret-copier
      restartPolicy: OnFailure
      containers:
        - name: copier
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Waiting for broker secret to be created..."
              for i in $(seq 1 30); do
                if kubectl get secret submariner-broker-submariner-k8s-broker-client-token -n submariner-k8s-broker >/dev/null 2>&1; then
                  echo "Broker secret found!"
                  break
                fi
                echo "Attempt $i/30: Secret not found yet, waiting..."
                sleep 2
              done
              
              echo "Extracting CA and token from broker secret..."
              CA=$(kubectl get secret submariner-broker-submariner-k8s-broker-client-token -n submariner-k8s-broker -o jsonpath='{.data.ca\.crt}')
              TOKEN=$(kubectl get secret submariner-broker-submariner-k8s-broker-client-token -n submariner-k8s-broker -o jsonpath='{.data.token}')
              
              # Handle IPSec PSK
              echo "Checking for existing IPSec PSK in broker namespace..."
              if kubectl get secret submariner-ipsec-psk -n submariner-k8s-broker >/dev/null 2>&1; then
                echo "Existing PSK found."
                PSK_BASE64=$(kubectl get secret submariner-ipsec-psk -n submariner-k8s-broker -o jsonpath='{.data.psk}')
              else
                echo "No PSK found. Generating new IPSec PSK..."
                # Generate a random alphanumeric string for PSK
                PSK=$(head -c 64 /dev/urandom | base64 | tr -d '\n')
                PSK_BASE64=$(echo -n "$PSK" | base64 | tr -d '\n')
                
                echo "Saving PSK to submariner-ipsec-psk in broker namespace..."
                cat <<EOF | kubectl apply -f -
              apiVersion: v1
              kind: Secret
              metadata:
                name: submariner-ipsec-psk
                namespace: submariner-k8s-broker
              type: Opaque
              data:
                psk: ${PSK_BASE64}
              EOF
              fi

              echo "Creating submariner-ipsec-psk in operator namespace..."
              cat <<EOF | kubectl apply -f -
              apiVersion: v1
              kind: Secret
              metadata:
                name: submariner-ipsec-psk
                namespace: submariner-operator
              type: Opaque
              data:
                psk: ${PSK_BASE64}
              EOF

              echo "Creating submariner-broker-secret in operator namespace..."
              cat <<EOF | kubectl apply -f -
              apiVersion: v1
              kind: Secret
              metadata:
                name: submariner-broker-secret
                namespace: submariner-operator
              type: Opaque
              data:
                ca.crt: ${CA}
                token: ${TOKEN}
              EOF
              
              echo "Secrets successfully copied and configured!"
