---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [nginx-public-ingressclass.yaml, nginx-public-service.yaml, nginx-public-deployment.yaml,clusterissuer-letsencrypt-public.yaml]
