---
namespace: mip-common-datacatalog
managed_cluster: true
datacatalog_images:
  repository: madgik
  tag: 1.2.0
dqt:
  flaskEnv: development
  flaskDebug: '1'
datacatalogDb:
  storageClassName: ceph-corbo-cephfs
  image: postgres:15
  db: datacatalog
  storage: 5Gi
backend:
  dbUrl: jdbc:postgresql://datacatalogdb:5432/datacatalog
  publicHost: datacatalogue.mip.ebrains.eu
  dqtUrl: http://data-quality-tool:8000
  authentication: 'true'
  keycloak:
    authUrl: https://iam.ebrains.eu/auth/
    realm: MIP
    sslRequired: none
persistence:
  enabled: true
  accessModes: [ReadWriteOnce]
