---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exareme2
  namespace: argocd-mip-team
spec:
  project: mip-argo-project-federation-a
  destination:
    namespace: federation-a
  sources:
    - repoURL: https://github.com/madgik/exareme2
      targetRevision: c1d4eb3d9d90edcf868a3a6395cc37b19c934e66  # 0.28.0
      path: kubernetes
      helm:
        valueFiles:
          - values.yaml
          - $values/deployments/shared-apps/exareme2/values.yaml
          - $values/deployments/local/federations/federation-A/customizations/exareme2-values.yaml
    - repoURL: https://github.com/NeuroTech-Platform/mip-infra.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions: [CreateNamespace=true, ApplyOutOfSyncOnly=true]
    automated:
      selfHeal: true
