---
log_level: DEBUG
managed_cluster: true
namespace: federation-a
engines:
  exareme2:
    URL: http://exareme2-controller-service:5000
mip:
  LINK: direct
  EXTERNAL_PROTOCOL: http
  PUBLIC_PROTOCOL: http
  PUBLIC_HOST: mip-frontend.mip-tds.chuv.cscs.ch
keycloak:
  AUTHENTICATION: 1
  INTERNAL_AUTH: 0
  PROTOCOL: https
  URL: iam.ebrains.eu
  REALM: MIP
  SSL_REQUIRED: external
frontend:
  DATACATALOG_PROTOCOL: http
  DATACATALOG_HOST: datacatalog.mip-tds.chuv.cscs.ch
