---
# Customizations for mip-stack in federation-a
# Example
# replicaCount: 3
# image:
#   tag: latest
# resources:
#   limits:
#     cpu: "2"
#     memory: "2Gi"
#   requests:
#     cpu: "1"
#     memory: "1Gi"
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mip-stack
  namespace: argocd-mip-team
spec:
  project: mip-argo-project-federation-a
  destination:
    namespace: federation-a
  sources:
    - repoURL: https://github.com/HBPMedical/mip-deployment
      targetRevision: f1bfbc187fb798c5ec9f4a12d600e503a08c7df5
      path: kubernetes
      helm:
        valueFiles:
          - values.yaml
          - $values/deployments/shared-apps/mip-stack/values.yaml
          - $values/deployments/local/federations/federation-A/customizations/mip-stack-values.yaml
    - repoURL: https://github.com/NeuroTech-Platform/mip-infra.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions: [CreateNamespace=true, ApplyOutOfSyncOnly=true]
    automated:
      selfHeal: true
