---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This name will be overridden by the federation-specific kustomize patch
  name: mip-stack
  namespace: argocd-mip-team
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  sources:
    - repoURL: https://github.com/HBPMedical/mip-deployment
      targetRevision: f7c64415c48f56bdb25188721d5857a5d79e2547
      path: kubernetes
      helm:
        valueFiles:
          - values.yaml
          - $values/deployments/shared-apps/mip-stack/values.yaml
    - repoURL: https://github.com/NeuroTech-Platform/mip-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    # This will be overridden by the federation-specific kustomize patch
    namespace: placeholder-namespace
  syncPolicy:
    syncOptions: [CreateNamespace=true, ApplyOutOfSyncOnly=true]
    automated:
      selfHeal: true
