---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This name will be overridden by the federation-specific kustomize patch
  name: mip-stack
  namespace: argocd-mip-team
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  sources:
    - repoURL: https://github.com/HBPMedical/mip-deployment
      targetRevision: managed_cluster
      path: kubernetes
      helm:
        valueFiles:
          - values.yaml
          - $values/deployments/shared-apps/mip-stack/values.yaml
    - repoURL: git@github.com:NeuroTech-Platform/mip-deployments.git
      targetRevision: dev/initial_setup_for_mip_deployments
      ref: values
  destination:
    server: https://kubernetes.default.svc
    # This will be overridden by the federation-specific kustomize patch
    namespace: placeholder-namespace
  syncPolicy:
    syncOptions: 
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true
