---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This name will be overridden by the federation-specific kustomize patch
  name: mip-stack
  namespace: argocd-mip-team
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  sources:
    - repoURL: https://github.com/HBPMedical/mip-deployment
      targetRevision: f1bfbc187fb798c5ec9f4a12d600e503a08c7df5
      path: kubernetes
      helm:
        valueFiles:
          - values.yaml
          - $values/deployments/shared-apps/mip-stack/values.yaml
    - repoURL: git@github.com:NeuroTech-Platform/mip-deployments.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    # This will be overridden by the federation-specific kustomize patch
    namespace: placeholder-namespace
  syncPolicy:
    syncOptions: [CreateNamespace=true, ApplyOutOfSyncOnly=true]
    automated:
      selfHeal: true
