---
managed_cluster: true
log_level: INFO
engines:
  exareme2:
    URL: http://exareme2-controller-service:5000
mip:
  LINK: direct
  EXTERNAL_PROTOCOL: http
  PUBLIC_PROTOCOL: http
datacatalog:
  PROTOCOL: https
  HOST: datacatalogue.mip.ebrains.eu
keycloak:
  AUTHENTICATION: 1
  INTERNAL_AUTH: 0
  PROTOCOL: https
  URL: iam.ebrains.eu
  REALM: MIP
  SSL_REQUIRED: external
