---
federationName: federation-a  # This will be overridden by ApplicationSet
# Default repositories that all federations can use
sourceRepos:
  - https://github.com/NeuroTech-Platform/mip-infra.git
  - git@github.com:NeuroTech-Platform/mip-deployments.git
  - https://github.com/madgik/exareme2
  - https://github.com/HBPMedical/mip-deployment
# Default server for single-cluster deployments
server: https://kubernetes.default.svc
# Default resource whitelists
resources:
  cluster:
    - group: ''
      kind: Namespace
  namespace:
    - group: argoproj.io
      kind: Application
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: apps
      kind: DaemonSet
    - group: apps
      kind: ReplicaSet
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: PersistentVolumeClaim
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: Pod
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
    - group: extensions
      kind: Ingress
  # Explicitly blacklist sensitive resources that should not be modified by federation applications
  blacklist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
# Default RBAC groups
rbac:
  adminGroups: [argocd-admins]
  developerGroups: [argocd-developers]
