---
# Static AppProjects ApplicationSet
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mip-argo-projects
  namespace: argocd-mip-team
  labels:
    app.kubernetes.io/managed-by: argocd
    argocd.instance: mip-team
  annotations:
    argocd.argoproj.io/note: 'Manages static AppProjects: mip-federations, mip-shared-apps,
      mip-common, mip-security'
spec:
  generators:
    - list:
        elements:
          - projectName: mip-argo-project-federations
            fileName: mip-federations
          - projectName: mip-argo-project-shared-apps
            fileName: mip-shared-apps
          - projectName: mip-argo-project-common
            fileName: mip-common
          - projectName: mip-argo-project-security
            fileName: mip-security
  goTemplate: true
  template:
    metadata:
      name: '{{ .projectName }}-app'
      labels:
        app.kubernetes.io/part-of: mip-argo-projects
        app.kubernetes.io/managed-by: argocd
    spec:
      project: mip-argo-project-infrastructure
      source:
        repoURL: https://github.com/NeuroTech-Platform/mip-infra.git
        targetRevision: dev/initial_setup_for_mip_deployments
        path: projects/static/{{ .fileName }}
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd-mip-team
      syncPolicy:
        syncOptions: [CreateNamespace=true]
        automated:
          selfHeal: true
---
# Dynamic Federation AppProjects ApplicationSet
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mip-argo-projects-of-federations
  namespace: argocd-mip-team
  labels:
    app.kubernetes.io/managed-by: argocd
    argocd.instance: mip-team
  annotations:
    argocd.argoproj.io/note: Generates federation-specific AppProjects dynamically
spec:
  generators:
    - git:
        repoURL: git@github.com:NeuroTech-Platform/mip-deployments.git
        revision: dev/initial_setup_for_mip_deployments
        directories:
          - path: deployments/local/federations/*
          - path: deployments/hybrid/federations/*/mip-infrastructure
  goTemplate: true
  template:
    metadata:
      name: argo-project-{{ if contains "local" .path.path }}{{ .path.basename | lower }}-local{{ else }}{{ .path.path | dir | base | lower }}-hybrid{{ end }}-app
      labels:
        app.kubernetes.io/part-of: argo-project-{{ if contains "local" .path.path }}{{ .path.basename | lower }}-local{{ else }}{{ .path.path | dir | base | lower }}-hybrid{{ end }}
        app.kubernetes.io/managed-by: argocd
    spec:
      project: mip-argo-project-infrastructure
      source:
        repoURL: https://github.com/NeuroTech-Platform/mip-infra.git
        targetRevision: dev/initial_setup_for_mip_deployments
        path: projects/templates/federation
        helm:
          valueFiles: [values.yaml]
          parameters:
            - name: federationName
              value: '{{ if contains "local" .path.path }}{{ .path.basename | lower }}{{ else }}{{ .path.path | dir | base | lower }}{{ end }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd-mip-team
      syncPolicy:
        syncOptions: [CreateNamespace=true]
        automated:
          selfHeal: true
---
# default should not be allowed anything
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
spec:
  sourceRepos: []
  sourceNamespaces: []
  destinations: []
  namespaceResourceBlacklist:
    - group: '*'
      kind: '*'
  clusterResourceBlacklist:
    - group: '*'
      kind: '*'
