---
apiVersion: v2
name: eck-stack-rke2
description: Helm chart to install the Elastic Cloud on Kubernetes (ECK) operator
  and sample Elastic Stack resources on an RKE2 cluster
kubeVersion: '>=1.23.0-0'
type: application
version: 0.2.0
appVersion: 2.13.0
icon: https://www.elastic.co/static/images/elastic-logo-200.png
keywords: [elasticsearch, eck, elastic-stack, operator]
dependencies: []
